### ISSUE TITLE
What should the ['REDIRECT_URI'] be set to?

### ISSUE THREAD

**Issue by dariushazimi** [uiucanh/streamlit-google-oauth#1]
Hi @uiucanh 

I am trying to implement the google auth with my streamlit app that is deployed on Heroku.
Will this solution still work with having the streamlit app deployed on Heroku?

If yes, I am not sure what to set the redirect_URI on the google site to?

Could you please provide some more info on this ?

Thanks

**Comment by duc-bui-ha** [comment]
Hi @dariushazimi 

The redirect_uri should be the URL of your Heroku deployment where you want the user to be redirected back to, e.g. `http:/example.herokuapp.com/`

**Comment by dariushazimi** [comment]
Hi @duc-bui-ha 

Thanks for the quick reply. I got it to work but the users can easily bypass the login anyway.

Here is what I have.

1. Deployed the app locally.
2. Created the google auth credentials and added them to the env
3. When I ran the app locally, localhost:8502 I get a url to login via google and after authentication, I am redirected to redirect_url of http://example.herokuapp.com

But I want to deploy the app on **Heroku** and run it from _**Heroku**_. so that when users go to example.herokuapp.com, they are forced to log in.

Right now, only I can do that on localhost. How can I implement the same when the app is running on Heroku?

I hope it is clear.

Does that make sense?
Thanks

**Comment by dariushazimi** [comment]
Hi @duc-bui-ha 
Let me know if you want to do a zoom call and I can share screen and show you. 

Thanks

**Comment by duc-bui-ha** [comment]
Hi, @dariushazimi 

Yes that's very clear. All you need to do is set `REDIRECT_URI` as an environment variable. 
- Locally, you set it to `localhost:8502` so that when you ran the app locally you get redirected back to that address. 
- When you deploy the Heroku app, you would set the environment variable to http://example.herokuapp.com so that users using the deployed app would get redirected back to that address. You can take a look at setting environment variables for Heroku app [here](https://devcenter.heroku.com/articles/config-vars).

Hope that helps.

**Comment by dariushazimi** [comment]
Thank you @duc-bui-ha 
So just to be sure:

My starting page would be = http://example.herokuapp.com
Also my redirect would be = http://example.herokuapp.com

GCP: I set the redirect in google gcp 
Heroku: and I set the environment variable to http://example.herokuapp.com in heroku

I get on it and see if I can make it work.
Thanks again

**Comment by dariushazimi** [comment]
Hi @duc-bui-ha 

It works fine.

Works great. Thank you.
